name: Build and release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-push:
    if: "!(contains(github.event.head_commit.message, 'chore(release): bump') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Get latest commit information
        id: message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s%n%n%b")
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Increase version for release
        run: |
          npm version patch -m "chore(release): bump to %s"
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull with rebase before pushing
        run: git pull --rebase origin master

      - name: Use new version
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Tag and push Docker image
        if: success()
        working-directory: docker/prod
        run: |
          docker buildx bake \
            --allow=fs.read=/home/runner/work \
            -f docker-compose.prod.yml \
            --set web.platform=linux/amd64,linux/arm64 \
            --set web.tags=${{ secrets.DOCKERHUB_USERNAME }}/eventdrop-web:latest \
            --set web.tags+=${{ secrets.DOCKERHUB_USERNAME }}/eventdrop-web:${{ steps.get-version.outputs.version }} \
            --set api.platform=linux/amd64,linux/arm64 \
            --set api.tags=${{ secrets.DOCKERHUB_USERNAME }}/eventdrop-api:latest \
            --set api.tags+=${{ secrets.DOCKERHUB_USERNAME }}/eventdrop-api:${{ steps.get-version.outputs.version }} \
            --push

      - name: Push version and tag
        if: success()
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD
          git push origin --tags

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
          tag_name: ${{ steps.get-version.outputs.version }}
          body: ${{ steps.message.outputs.message }}
          name: "Release ${{ steps.get-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
